/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int BALLOONS = 12;
  /** RegularExpression Id. */
  int CHIPS = 13;
  /** RegularExpression Id. */
  int DEFVAR = 14;
  /** RegularExpression Id. */
  int DEFPROC = 15;
  /** RegularExpression Id. */
  int JUMP = 16;
  /** RegularExpression Id. */
  int WALK = 17;
  /** RegularExpression Id. */
  int LEAP = 18;
  /** RegularExpression Id. */
  int TURN = 19;
  /** RegularExpression Id. */
  int TURNT = 20;
  /** RegularExpression Id. */
  int DROP = 21;
  /** RegularExpression Id. */
  int GET = 22;
  /** RegularExpression Id. */
  int GRAB = 23;
  /** RegularExpression Id. */
  int LETGO = 24;
  /** RegularExpression Id. */
  int NOP = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int WHILE = 28;
  /** RegularExpression Id. */
  int REPEAT = 29;
  /** RegularExpression Id. */
  int TIMES = 30;
  /** RegularExpression Id. */
  int CAN = 31;
  /** RegularExpression Id. */
  int FACING = 32;
  /** RegularExpression Id. */
  int NOT = 33;
  /** RegularExpression Id. */
  int DIRECTION = 34;
  /** RegularExpression Id. */
  int ORIENTATION = 35;
  /** RegularExpression Id. */
  int LETRA = 36;
  /** RegularExpression Id. */
  int DIGIT = 37;
  /** RegularExpression Id. */
  int NUM = 38;
  /** RegularExpression Id. */
  int VAR = 39;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"Defvar\"",
    "\"Defproc\"",
    "\"jump\"",
    "\"walk\"",
    "\"leap\"",
    "\"turn\"",
    "\"turnto\"",
    "\"drop\"",
    "\"get\"",
    "\"grab\"",
    "\"letgo\"",
    "\"nop\"",
    "\"If\"",
    "\"Else\"",
    "\"While\"",
    "\"Repeat\"",
    "\"Times\"",
    "\"Can\"",
    "\"Facing\"",
    "\"Not\"",
    "<DIRECTION>",
    "<ORIENTATION>",
    "<LETRA>",
    "<DIGIT>",
    "<NUM>",
    "<VAR>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
